[package]
name = "gen"
description = "a simple & secure cli password/passphrase generator"
repository = "https://github.com/succumbs/gen"
license = "MIT"
authors = ["June"]
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
rand = "0.8.5"